on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"

name: "Daily analysis"
jobs:
  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run index.ts
